# Generated by Django 2.2.19 on 2021-02-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('T-SHIRT', 'T-Shirt'), ('SHIRT', 'Shirt'), ('SWEATER', 'Sweater'), ('JEANS', 'Jeans'), ('PANTS', 'Pants'), ('SKIRT', 'Skirt'), ('JEANS', 'Jacket'), ('SHOES', 'Shoes'), ('SOCKS', 'Socks')], max_length=20)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNISEX', 'Unisex')], max_length=10)),
                ('brand', models.CharField(max_length=50)),
            ],
        ),
    ]
