# Generated by Django 2.2.19 on 2021-02-23 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210223_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('BLUE', 'Blue'), ('RED', 'Red'), ('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('BROWN', 'Brown'), ('ORANGE', 'Orange'), ('PINK', 'Pink'), ('BLACK', 'Black'), ('WHITE', 'White'), ('GREY', 'Grey'), ('PURPLE', 'Purple')], max_length=10)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ProductVariant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('color', 'store'), name='variant'),
        ),
        migrations.AddConstraint(
            model_name='productinstock',
            constraint=models.UniqueConstraint(fields=('size', 'product_variant'), name='size_details'),
        ),
    ]
