# Generated by Django 2.2.19 on 2021-03-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210301_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('man', 'Man'), ('woman', 'Woman')], max_length=10),
        ),
    ]
