# Generated by Django 2.2.19 on 2021-03-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210301_2102'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='variant',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='store',
            new_name='product',
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('color', 'product'), name='variant'),
        ),
    ]
