# Generated by Django 2.2.19 on 2021-03-07 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210307_0358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductInStock',
            new_name='ItemInStock',
        ),
        migrations.RenameModel(
            old_name='ProductVariant',
            new_name='ItemVariant',
        ),
    ]
