# Generated by Django 2.2.19 on 2021-03-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210307_0404'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemvariant',
            name='variant',
        ),
        migrations.RenameField(
            model_name='itemvariant',
            old_name='product',
            new_name='item',
        ),
        migrations.AddConstraint(
            model_name='itemvariant',
            constraint=models.UniqueConstraint(fields=('color', 'item'), name='variant'),
        ),
    ]
