# Generated by Django 2.2.19 on 2021-03-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210307_0406'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='iteminstock',
            name='size_details',
        ),
        migrations.RenameField(
            model_name='iteminstock',
            old_name='product_variant',
            new_name='item_variant',
        ),
        migrations.AddConstraint(
            model_name='iteminstock',
            constraint=models.UniqueConstraint(fields=('size', 'item_variant'), name='size_details'),
        ),
    ]
