# Generated by Django 2.2.19 on 2021-03-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('t-shirt', 'T-Shirt'), ('shirt', 'Shirt'), ('sweater', 'Sweater'), ('sweatshirt', 'Sweatshirt'), ('jeans', 'Jeans'), ('pants', 'Pants'), ('jacket', 'Jacket'), ('shoes', 'Shoes'), ('socks', 'Socks')], max_length=20),
        ),
    ]
