# Generated by Django 2.2.19 on 2021-03-07 06:52

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=autoslug.fields.AutoSlugField(unique_with=['category', 'brand', 'gender']),
        ),
    ]
