# Generated by Django 2.2.19 on 2021-03-23 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0022_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('T-Shirt', 'T-Shirt'), ('Shirt', 'Shirt'), ('Sweater', 'Sweater'), ('Sweatshirt', 'Sweatshirt'), ('Jeans', 'Jeans'), ('Pants', 'Pants'), ('Jacket', 'Jacket'), ('Shoes', 'Shoes'), ('Socks', 'Socks')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman')], max_length=10),
        ),
        migrations.AlterField(
            model_name='iteminstock',
            name='size',
            field=models.CharField(choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5),
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='store.ItemInStock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
