# Generated by Django 2.2.19 on 2021-03-23 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20210323_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='items',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ItemInStock')),
            ],
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='order_items',
            field=models.ManyToManyField(to='store.OrderItem'),
        ),
    ]
