# Generated by Django 2.2.19 on 2021-03-23 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20210323_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
