# Generated by Django 2.2.19 on 2021-05-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('T-Shirt', 'T-Shirt'), ('Shirt', 'Shirt'), ('Sweater', 'Sweater'), ('Sweatshirt', 'Sweatshirt'), ('Jeans', 'Jeans'), ('Pants', 'Pants'), ('Jacket', 'Jacket'), ('Socks', 'Socks')], max_length=20),
        ),
    ]
